[package]
name = "aeko-token-20-program"
description = "AEKO-20 fungible token program"
documentation = "https://github.com/MilliHub-dev/aeko-chain/tree/main/programs/token-20"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true }
aeko-program = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-tokenomics-program = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_token_20_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
