//! `/registry/social` exposes the canonical AEKO SocialFi state-account registry.
//!
//! Production deployment has two sources, in precedence order:
//!   1. explicit `AEKO_SOCIAL_*` environment variables supplied by an operator;
//!   2. the registry file generated by `aeko-social-bootstrap` and mounted into
//!      the explorer container via `AEKO_SOCIAL_REGISTRY_FILE`.
//!
//! The file path removes the old manual copy/paste step between bootstrap and
//! explorer while preserving environment variables as an intentional override.

use {
    crate::{error::ApiResult, response, state::SharedState},
    axum::{extract::State, routing::get, Json, Router},
    serde::Serialize,
    std::{collections::HashMap, env, fs},
};

const REGISTRY_FILE_ENV: &str = "AEKO_SOCIAL_REGISTRY_FILE";

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SocialRegistry {
    pub posts: Option<String>,
    pub rewards: Option<String>,
    pub staking: Option<String>,
    pub anti_spam: Option<String>,
    pub monetization: Option<String>,
    pub reward_vault: Option<String>,
    pub treasury: Option<String>,
    pub platform_fee_bps: Option<u32>,
    pub complete: bool,
}

pub fn router() -> Router<SharedState> {
    Router::new().route("/registry/social", get(get_social_registry))
}

async fn get_social_registry(
    State(state): State<SharedState>,
) -> ApiResult<Json<response::DataEnvelope<SocialRegistry>>> {
    Ok(response::data(&state.network, resolve_social_registry()))
}

pub(crate) fn resolve_social_registry() -> SocialRegistry {
    let file_values = load_registry_file();
    let read = |key: &str| read_value(key, &file_values);

    let posts = read("AEKO_SOCIAL_POSTS_STATE");
    let rewards = read("AEKO_SOCIAL_REWARDS_STATE");
    let staking = read("AEKO_SOCIAL_STAKING_STATE");
    let anti_spam = read("AEKO_SOCIAL_ANTI_SPAM_STATE");
    let monetization = read("AEKO_SOCIAL_MONETIZATION_STATE");
    let complete = posts.is_some()
        && rewards.is_some()
        && staking.is_some()
        && anti_spam.is_some()
        && monetization.is_some();

    SocialRegistry {
        posts,
        rewards,
        staking,
        anti_spam,
        monetization,
        reward_vault: read("AEKO_REWARD_VAULT_ACCOUNT"),
        treasury: read("AEKO_TREASURY_ADDRESS"),
        platform_fee_bps: read("AEKO_PLATFORM_FEE_BPS").and_then(|s| s.parse().ok()),
        complete,
    }
}

fn read_value(key: &str, file_values: &HashMap<String, String>) -> Option<String> {
    env::var(key)
        .ok()
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
        .or_else(|| file_values.get(key).cloned())
}

fn load_registry_file() -> HashMap<String, String> {
    let Some(path) = env::var(REGISTRY_FILE_ENV)
        .ok()
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
    else {
        return HashMap::new();
    };

    fs::read_to_string(path)
        .map(|content| parse_registry_env(&content))
        .unwrap_or_default()
}

fn parse_registry_env(content: &str) -> HashMap<String, String> {
    content
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                return None;
            }
            let line = line.strip_prefix("export ").unwrap_or(line);
            let (key, value) = line.split_once('=')?;
            let key = key.trim();
            let value = value.trim();
            if key.is_empty() || value.is_empty() {
                return None;
            }
            Some((key.to_string(), value.to_string()))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::parse_registry_env;

    #[test]
    fn registry_file_parser_accepts_bootstrap_format() {
        let values = parse_registry_env(
            r#"
# generated by aeko-social-bootstrap
AEKO_SOCIAL_POSTS_STATE=posts111
export AEKO_SOCIAL_REWARDS_STATE=rewards222
AEKO_SOCIAL_STAKING_STATE=staking333
AEKO_SOCIAL_ANTI_SPAM_STATE=anti444
AEKO_SOCIAL_MONETIZATION_STATE=monet555
EMPTY=
"#,
        );

        assert_eq!(values.get("AEKO_SOCIAL_POSTS_STATE").map(String::as_str), Some("posts111"));
        assert_eq!(values.get("AEKO_SOCIAL_REWARDS_STATE").map(String::as_str), Some("rewards222"));
        assert_eq!(values.get("AEKO_SOCIAL_STAKING_STATE").map(String::as_str), Some("staking333"));
        assert_eq!(values.get("AEKO_SOCIAL_ANTI_SPAM_STATE").map(String::as_str), Some("anti444"));
        assert_eq!(values.get("AEKO_SOCIAL_MONETIZATION_STATE").map(String::as_str), Some("monet555"));
        assert!(!values.contains_key("EMPTY"));
    }
}
