import { useCallback, useEffect, useState } from 'react'
import { LoaderCircle } from 'lucide-react'
import type { StudioConfig } from '../shared/contracts/session.js'
import type { CreateWorkspaceRequest, Workspace as WorkspaceContract } from '../shared/contracts/workspace.js'
import { errorMessage } from '../shared/errors/editor-errors.js'
import { Alert, AlertDescription } from './components/ui/alert'
import LoginGate from './components/LoginGate'
import WorkspaceLauncher from './components/WorkspaceLauncher'
import Workspace from './ide/Workspace'
import { api } from './lib/api'
function Loading({label}:{label:string}){return <div className="flex size-full flex-col bg-background text-foreground" role="status" aria-live="polite"><header className="flex h-14 shrink-0 items-center gap-3 border-b border-border px-4"><div className="grid size-8 place-items-center rounded-lg bg-primary font-black text-primary-foreground">A</div><div><strong className="block text-sm">AEKO Studio</strong><span className="text-xs text-muted-foreground">{label}</span></div></header><div className="flex min-h-0 flex-1"><aside className="flex w-14 flex-col items-center gap-3 border-r border-border py-4">{Array.from({length:6},(_,index)=><span key={index} className="size-9 animate-pulse rounded-lg bg-muted motion-reduce:animate-none"/>)}</aside><aside className="hidden w-64 border-r border-border p-4 lg:block"><div className="h-4 w-24 animate-pulse rounded bg-muted motion-reduce:animate-none"/><div className="mt-5 space-y-3">{Array.from({length:8},(_,index)=><div key={index} className={['h-3 w-3/5 animate-pulse rounded bg-muted motion-reduce:animate-none','h-3 w-3/4 animate-pulse rounded bg-muted motion-reduce:animate-none','h-3 w-11/12 animate-pulse rounded bg-muted motion-reduce:animate-none'][index%3]}/>)}</div></aside><main className="relative min-w-0 flex-1"><div className="absolute inset-0 grid place-items-center"><div className="flex items-center gap-3 rounded-lg border border-border bg-card px-4 py-3 text-sm shadow-lg"><LoaderCircle className="size-5 animate-spin text-primary motion-reduce:animate-none"/><span>{label}</span></div></div></main></div></div>}
export default function App(){const[config,setConfig]=useState<StudioConfig|null>(null);const[authenticated,setAuthenticated]=useState<boolean|null>(null);const[workspaces,setWorkspaces]=useState<WorkspaceContract[]>([]);const[workspaceId,setWorkspaceId]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const loadWorkspaces=useCallback(async()=>{const data=await api.listWorkspaces();setWorkspaces(data.workspaces);return data.workspaces},[]);const verify=useCallback(async()=>{try{const[nextConfig,session]=await Promise.all([api.config(),api.session()]);setConfig(nextConfig);setAuthenticated(session.authenticated);if(session.authenticated)await loadWorkspaces()}catch(cause){setError(errorMessage(cause,'Contract Studio could not start.'));setAuthenticated(false)}},[loadWorkspaces]);useEffect(()=>{void verify()},[verify]);const createWorkspace=async(input:CreateWorkspaceRequest)=>{setBusy(true);setError('');try{const workspace=await api.createWorkspace(input);setWorkspaces(current=>[workspace,...current]);setWorkspaceId(workspace.id)}catch(cause){setError(errorMessage(cause))}finally{setBusy(false)}};const deleteWorkspace=async(workspace:WorkspaceContract)=>{if(!window.confirm('Delete '+workspace.name+' and all files in its isolated workspace?'))return;setBusy(true);setError('');try{await api.deleteWorkspace(workspace.id);await loadWorkspaces();if(workspaceId===workspace.id)setWorkspaceId('')}catch(cause){setError(errorMessage(cause))}finally{setBusy(false)}};const logout=async()=>{await api.logout().catch(()=>undefined);setAuthenticated(false);setWorkspaces([]);setWorkspaceId('')};if(authenticated===null)return <Loading label="Starting AEKO Contract Studio…"/>;if(!authenticated)return <LoginGate config={config} onAuthenticated={verify}/>;if(!config)return <Loading label="Loading Contract Studio configuration…"/>;const workspace=workspaces.find(item=>item.id===workspaceId);if(!workspace)return <><WorkspaceLauncher workspaces={workspaces} onOpen={setWorkspaceId} onCreate={createWorkspace} onDelete={deleteWorkspace} busy={busy}/>{error?<div className="fixed bottom-4 right-4 w-[min(28rem,calc(100vw-2rem))]"><Alert className="border-destructive"><AlertDescription className="text-destructive">{error}</AlertDescription></Alert></div>:null}</>;return <Workspace workspace={workspace} config={config} onHome={()=>setWorkspaceId('')} onLogout={logout}/>}
