[package]
name = "aeko-rust-sdk"
description = "AEKO Chain high-level Rust developer SDK"
documentation = "https://docs.rs/aeko-rust-sdk"
readme = "README.md"
version = "2.0.2"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
keywords = ["aeko", "blockchain", "sdk", "rpc", "wallet"]

[dependencies]
base64 = { workspace = true }
borsh = { workspace = true }
bs58 = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lib]
crate-type = ["rlib"]
name = "aeko_rust_sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
