// Network endpoints are deployment configuration, not application constants.
// Production images read window.__AEKO_RUNTIME_CONFIG__, generated by the
// container entrypoint from Coolify/Docker environment variables. VITE_* values
// are retained only for local Vite development and CI preview builds.

const runtime = globalThis.__AEKO_RUNTIME_CONFIG__ || {};
const vite = import.meta.env || {};

const configured = (runtimeKey, viteKey) =>
  String(runtime[runtimeKey] || vite[viteKey] || '').trim();

const browserOrigin =
  typeof globalThis.location?.origin === 'string' ? globalThis.location.origin : '';

const LOCAL_DEFAULTS = {
  rpc: 'http://127.0.0.1:8899',
  ws: 'ws://127.0.0.1:8900',
  explorer: 'http://127.0.0.1:4000',
  explorerApi: 'http://127.0.0.1:8088',
};

const LOCAL_OVERRIDE = {
  rpc: configured('localRpcUrl', 'VITE_AEKO_LOCAL_RPC'),
  ws: configured('localWebsocketUrl', 'VITE_AEKO_LOCAL_WS'),
  explorerApi: configured('localExplorerApiUrl', 'VITE_AEKO_LOCAL_EXPLORER_API'),
};
const localOverrideValues = Object.values(LOCAL_OVERRIDE);
const hasAnyLocalOverride = localOverrideValues.some(Boolean);
const hasCompleteLocalOverride = localOverrideValues.every(Boolean);

if (hasAnyLocalOverride && !hasCompleteLocalOverride) {
  throw new Error(
    'AEKO local endpoint overrides are atomic: set local RPC, WebSocket, and Explorer API together.',
  );
}

function isLoopbackEndpoint(value) {
  if (!value) return false;
  const hostname = new URL(value).hostname.toLowerCase();
  return hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '::1';
}

if (hasCompleteLocalOverride && !localOverrideValues.every(isLoopbackEndpoint)) {
  throw new Error('AEKO local endpoint overrides must be loopback endpoints.');
}

const forceIsolatedDev =
  Boolean(vite.DEV) && vite.VITE_AEKO_ALLOW_REMOTE_IN_DEV !== 'true';
const useLocalEndpoints = hasCompleteLocalOverride || forceIsolatedDev;

const PUBLIC_TESTNET = {
  rpc: configured('rpcUrl', 'VITE_AEKO_TESTNET_RPC'),
  ws: configured('websocketUrl', 'VITE_AEKO_TESTNET_WS'),
  explorer: configured('explorerUrl', 'VITE_AEKO_TESTNET_EXPLORER') || browserOrigin,
  explorerApi: configured('explorerApiUrl', 'VITE_AEKO_TESTNET_EXPLORER_API'),
  funding: configured('fundingUrl', 'VITE_AEKO_TESTNET_FUNDING_URL'),
};

const TESTNET_RUNTIME = useLocalEndpoints
  ? {
      rpc: LOCAL_OVERRIDE.rpc || LOCAL_DEFAULTS.rpc,
      ws: LOCAL_OVERRIDE.ws || LOCAL_DEFAULTS.ws,
      explorer: LOCAL_DEFAULTS.explorer,
      explorerApi: LOCAL_OVERRIDE.explorerApi || LOCAL_DEFAULTS.explorerApi,
      funding: '',
    }
  : PUBLIC_TESTNET;

const MAINNET_RUNTIME = {
  rpc: configured('mainnetRpcUrl', 'VITE_AEKO_MAINNET_RPC'),
  ws: configured('mainnetWebsocketUrl', 'VITE_AEKO_MAINNET_WS'),
  explorer: configured('mainnetExplorerUrl', 'VITE_AEKO_MAINNET_EXPLORER'),
  explorerApi: configured('mainnetExplorerApiUrl', 'VITE_AEKO_MAINNET_EXPLORER_API'),
};
const mainnetAvailable = Object.values(MAINNET_RUNTIME).every(Boolean);
const testnetAvailable = Boolean(
  TESTNET_RUNTIME.rpc
  && TESTNET_RUNTIME.ws
  && TESTNET_RUNTIME.explorer
  && TESTNET_RUNTIME.explorerApi,
);

export const NETWORKS = {
  mainnet: {
    key: 'mainnet',
    label: mainnetAvailable ? 'Mainnet' : 'Mainnet (not configured)',
    available: mainnetAvailable,
    rpcUrl: MAINNET_RUNTIME.rpc,
    websocketUrl: MAINNET_RUNTIME.ws,
    explorerUrl: MAINNET_RUNTIME.explorer,
    explorerApiUrl: MAINNET_RUNTIME.explorerApi,
    explorerLabel: MAINNET_RUNTIME.explorer ? new URL(MAINNET_RUNTIME.explorer).host : 'Not configured',
    fundingUrl: '',
    fundingLabel: 'No test funding on mainnet',
    fundingEnabled: false,
    cliCluster: MAINNET_RUNTIME.rpc,
  },
  testnet: {
    key: useLocalEndpoints ? 'localnet' : 'testnet',
    label: useLocalEndpoints ? 'Local AEKO Network' : 'Public Testnet',
    available: testnetAvailable,
    rpcUrl: TESTNET_RUNTIME.rpc,
    websocketUrl: TESTNET_RUNTIME.ws,
    explorerUrl: TESTNET_RUNTIME.explorer,
    explorerApiUrl: TESTNET_RUNTIME.explorerApi,
    explorerLabel: TESTNET_RUNTIME.explorer ? new URL(TESTNET_RUNTIME.explorer).host : 'Not configured',
    fundingUrl: TESTNET_RUNTIME.funding,
    fundingLabel: useLocalEndpoints
      ? 'Local funding uses requestAirdrop on the local RPC'
      : 'Policy-controlled Testnet Funding Portal',
    fundingEnabled: Boolean(TESTNET_RUNTIME.funding),
    cliCluster: TESTNET_RUNTIME.rpc,
  },
};

export function getNetworkConfig(network) {
  return NETWORKS[network] || NETWORKS.testnet;
}

export function isLocalNetworkConfig(config) {
  return config?.key === 'localnet';
}
