[package]
name = "aeko-social-rewards-program"
description = "AEKO Social creator rewards program"
documentation = "https://github.com/MilliHub-dev/aeko-chain/tree/main/programs/social-rewards"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true }
aeko-program = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }

[features]
default = []

[lib]
crate-type = ["lib"]
name = "aeko_social_rewards_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
