import { ChevronDown, ChevronUp, Maximize2, Minimize2 } from 'lucide-react'
import { useState } from 'react'
import StudioConsole from '../ide/StudioConsole'
import Terminal from '../ide/Terminal'
import { Button } from './ui/button'
import { cn } from '../lib/utils'
type Tab='TERMINAL'|'TASKS'
interface Props{workspaceId:string;collapsed:boolean;onToggleCollapsed:()=>void;maximized?:boolean;onToggleMaximized?:()=>void}
export default function BottomPanel({workspaceId,collapsed,onToggleCollapsed,maximized=false,onToggleMaximized}:Props){const[tab,setTab]=useState<Tab>('TERMINAL');return <section className="flex size-full min-h-0 flex-col border-t border-border bg-background"><header className="flex h-10 shrink-0 items-center justify-between px-2"><div className="flex h-full items-center gap-1">{(['TERMINAL','TASKS'] as const).map(item=><button key={item} type="button" className={cn('h-full cursor-pointer border-b-2 border-transparent px-3 text-xs font-medium text-muted-foreground hover:text-foreground',tab===item&&'border-primary text-foreground')} onClick={()=>{setTab(item);if(collapsed)onToggleCollapsed()}}>{item==='TERMINAL'?'BASH / AEKO CLI':'BUILD & RUN'}</button>)}</div><div className="flex items-center gap-1">{onToggleMaximized?<Button variant="ghost" size="icon" className="size-8" aria-label={maximized?'Restore panel':'Maximize panel'} onClick={onToggleMaximized}>{maximized?<Minimize2/>:<Maximize2/>}</Button>:null}<Button variant="ghost" size="icon" className="size-8" aria-label={collapsed?'Show panel':'Hide panel'} onClick={onToggleCollapsed}>{collapsed?<ChevronUp/>:<ChevronDown/>}</Button></div></header>{!collapsed?<div className="min-h-0 flex-1">{tab==='TERMINAL'?<Terminal workspaceId={workspaceId}/>:<StudioConsole workspaceId={workspaceId}/>}</div>:null}</section>}
