name: Build & Deploy Aeko Node to GHCR

on:
  push:
    branches: [ "main" ]

# Grants workflow permission to publish packages to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          # Convert repo name to lowercase to prevent GHCR naming errors and deploy
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/aeko-node:latest" | tr '[:upper:]' '[:lower:]')
          
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Trigger Dokploy Deployment
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}"
